//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.04 at 02:17:47 AM MSK 
//


package agregator;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for creditCard complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="creditCard">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cardNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardholdersName" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="validityMM" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="validityYY" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="CVC" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "creditCard", propOrder = {
    "cardNumber",
    "cardholdersName",
    "validityMM",
    "validityYY",
    "cvc"
})
public class CreditCard {

    @XmlElement(required = true)
    protected String cardNumber;
    protected double cardholdersName;
    protected double validityMM;
    protected double validityYY;
    @XmlElement(name = "CVC")
    protected double cvc;

    /**
     * Gets the value of the cardNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Sets the value of the cardNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardNumber(String value) {
        this.cardNumber = value;
    }

    /**
     * Gets the value of the cardholdersName property.
     * 
     */
    public double getCardholdersName() {
        return cardholdersName;
    }

    /**
     * Sets the value of the cardholdersName property.
     * 
     */
    public void setCardholdersName(double value) {
        this.cardholdersName = value;
    }

    /**
     * Gets the value of the validityMM property.
     * 
     */
    public double getValidityMM() {
        return validityMM;
    }

    /**
     * Sets the value of the validityMM property.
     * 
     */
    public void setValidityMM(double value) {
        this.validityMM = value;
    }

    /**
     * Gets the value of the validityYY property.
     * 
     */
    public double getValidityYY() {
        return validityYY;
    }

    /**
     * Sets the value of the validityYY property.
     * 
     */
    public void setValidityYY(double value) {
        this.validityYY = value;
    }

    /**
     * Gets the value of the cvc property.
     * 
     */
    public double getCVC() {
        return cvc;
    }

    /**
     * Sets the value of the cvc property.
     * 
     */
    public void setCVC(double value) {
        this.cvc = value;
    }

}
