//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.09 at 03:52:26 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:Agregator", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package agregator;
